env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - google
  - prettier
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: 12
  sourceType: module
ignorePatterns:
  - node_modules
  - dist
  - src/assets
  - data
  - .vscode
rules:
  prettier/prettier: 0
  no-async-promise-executor: off
  newline-before-return: error
  no-prototype-builtins: off
  prefer-rest-params: error
  no-param-reassign: error
  no-extend-native: off
  object-curly-spacing: off
  template-curly-spacing: error
  max-len: off
  eol-last: off
  padded-blocks:
    - error
    - classes: always
  valid-jsdoc: error
  require-jsdoc: off
  comma-dangle: off
  prefer-const: error
  prefer-template: error
  no-tabs: off
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  indent:
    - error
    - tab
    - SwitchCase: 1
  complexity:
    - error
    - 10
  max-params:
    - error
    - 5
  max-statements:
    - error
    - 25
  max-statements-per-line:
    - error
    - max: 1
  max-nested-callbacks:
    - error
    - 2
  max-depth:
    - error
    - max: 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always