export const SETTINGS = {
	// Rendering
	RENDER_DISTANCE: 16 ** 2, // Squared
	RENDER_CHUNKS: true,
	SORT_CHUNKS_BY_DISTANCE: false,

	// Texture
	TEXTURE_ATLAS_SIZE: 16,
	TEXTURE_ATLAS_SPRITE_SIZE: 16,
	TEXTURE_PADDING: 4,
	ANISOTROPIC_FILTERING: 16,
	USE_MSAA: true,

	// Terrain
	TERRAIN_GENERATION_SEED: "myseed",
	TERRAIN_GENERATION_ON_MAIN_THREAD: false,
	TERRAIN_GENERATION_WORKER_COUNT: 1,

	// Ray casting
	RAYCASTING_STEP: 1,
	RAYCASTING_MAX_DISTANCE: 10,
	RAYCASTING_USE_DDA: true,

	// Debug
	DISABLE_DEPTH_FOR_GIZMOS: false,
	RENDER_CHUNK_BOUNDS: false,
	RENDER_CHUNK_WIREFRAME: false,

	// Filters
	FILTER_COLOR_CORRECTION_ENABLED: true,
	FILTER_FXAA_ENABLED: false,
	FILTER_SHARPEN_ENABLED: false,

} as const;