export const SETTINGS = {
	// Rendering
	RENDER_DISTANCE: 16 ** 2,
	RENDER_CHUNKS: true,
	SORT_CHUNKS_BY_DISTANCE: true,
	ANSIOTROPIC_FILTERING: 0,

	// Terrain
	TERRAIN_GENERATION_SEED: "myseed",
	TERRAIN_GENERATION_ON_MAIN_THREAD: false,
	TERRAIN_GENERATION_WORKER_COUNT: 1,
	TERRAIN_GENERATION_PACK: true,


	// Debug
	DISABLE_DEPTH_FOR_GIZMOS: false,
	RENDER_CHUNK_BOUNDS: false,
	RENDER_CHUNK_WIREFRAME: false,

} as const;