export const SETTINGS = {
	// Rendering
	RENDER_DISTANCE: 16 ** 2,
	RENDER_CHUNKS: true,
	SORT_CHUNKS_BY_DISTANCE: false,

	// Texture
	TEXTURE_ATLAS_SIZE: 16,
	TEXTURE_ATLAS_SPRITE_SIZE: 16,
	TEXTURE_PADDING: 4,
	ANSIOTROPIC_FILTERING: 0,
	MSAA_SAMPLES: 0,

	// Terrain
	TERRAIN_GENERATION_SEED: "myseed",
	TERRAIN_GENERATION_ON_MAIN_THREAD: false,
	TERRAIN_GENERATION_WORKER_COUNT: 1,

	// Raycasting
	RAYCASTING_STEP: 1,
	RAYCASTING_MAX_DISTANCE: 10,
	RAYCASTING_USE_DDA: true,

	// Debug
	DISABLE_DEPTH_FOR_GIZMOS: false,
	RENDER_CHUNK_BOUNDS: false,
	RENDER_CHUNK_WIREFRAME: false,

} as const;