export enum Key {
	W = "KeyW",
	A = "KeyA",
	S = "KeyS",
	D = "KeyD",
	R = "KeyR",
	C = "KeyC",
	V = "KeyV",
	Shift = "ShiftLeft",
	Ctrl = "ControlLeft",
	Enter = "Enter",
	ArrowUp = "ArrowUp",
	ArrowDown = "ArrowDown",
	ArrowLeft = "ArrowLeft",
	ArrowRight = "ArrowRight",
	Space = "Space",
	Escape = "Escape",
	Quote = "Backquote",
	Backspace = "Backspace",
}
